# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hantaã®å¤©å¢ƒå°å±‹ğŸ¥
subtitle: 'å‘ç€é˜³å…‰ç”Ÿé•¿'
description: 'The boy who lived'
keywords: blog, hanta, developer, programming, technology, life
author: Hanta
language: zh-CN
timezone: 'Asia/Shanghai'
email: 2667174454@qq.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.hanta2011.top
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/exef-star/exef-star.github.io.git
  branch: main

# RSSè®¢é˜…ï¼šhttps://github.com/hexojs/hexo-generator-feed
feed:
  enable: true  # å¯ç”¨æˆ–ç¦ç”¨Feedæ’ä»¶ï¼Œtrueä¸ºå¯ç”¨ï¼Œfalseä¸ºç¦ç”¨
  type: # è®¾ç½®Feedçš„ç±»å‹ï¼Œå¯ä»¥æ˜¯atomæˆ–rss2ï¼Œæˆ–è€…ä¸¤è€…éƒ½è¾“å‡º
    - atom
    - rss2
  path: # è®¾ç½®Feedæ–‡ä»¶çš„è·¯å¾„ï¼Œå½“è¾“å‡ºä¸¤ç§ç±»å‹æ—¶ï¼Œéœ€è¦æŒ‰ç…§ç±»å‹é¡ºåºè®¾ç½®è·¯å¾„
    - atom.xml
    - rss2.xml
  limit: 0  # è®¾ç½®Feedä¸­æ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ä¸Šé™ï¼Œ0æˆ–falseè¡¨ç¤ºæ˜¾ç¤ºæ‰€æœ‰æ–‡ç« 
  hub:  # PubSubHubbubä¸­å¿ƒURLï¼Œå¦‚æœä¸ä½¿ç”¨å¯ä»¥ç•™ç©º
  content:  # æ˜¯å¦åœ¨Feedä¸­åŒ…å«æ–‡ç« å…¨æ–‡å†…å®¹ï¼Œtrueä¸ºåŒ…å«ï¼Œfalseä¸ºä¸åŒ…å«
  content_limit: 140  # è®¾ç½®Feedä¸­æ–‡ç« å†…å®¹çš„é•¿åº¦é™åˆ¶ï¼Œä»…å½“contentä¸ºfalseæ—¶æœ‰æ•ˆ
  content_limit_delim: ' '  # è®¾ç½®å†…å®¹é•¿åº¦é™åˆ¶çš„åˆ†å‰²ç¬¦ï¼Œé»˜è®¤ä¸ºç©ºæ ¼
  order_by: -date  # è®¾ç½®Feedä¸­æ–‡ç« çš„æ’åºæ–¹å¼ï¼Œé»˜è®¤æŒ‰æ—¥æœŸå€’åº
  icon: icon.png  # è®¾ç½®Feedçš„å›¾æ ‡ï¼Œé»˜è®¤ä½¿ç”¨_config.ymlä¸­æŒ‡å®šçš„ç”µå­é‚®ä»¶çš„gravatar
  autodiscovery: true  # æ˜¯å¦å¯ç”¨Feedçš„è‡ªåŠ¨å‘ç°åŠŸèƒ½ï¼Œtrueä¸ºå¯ç”¨ï¼Œfalseä¸ºç¦ç”¨
  template:  # è®¾ç½®è‡ªå®šä¹‰Feedæ¨¡æ¿çš„è·¯å¾„ï¼Œå¯ä»¥æŒ‡å®šä¸€ä¸ªæˆ–å¤šä¸ªæ¨¡æ¿

nofollow:
  enable: true
  field: site
  exclude:

sitemap:
  path: sitemap.xml

magnet:
  enable: true
  priority: 1
  enable_page: /
  type: tags
  devide: 2
  display:
    - name: Python
      display_name: Pythonå°ç©æ„
      icon: ğŸ“š
    - name: æ€»ç»“
      display_name: ä¸€äº›æ€»ç»“æ–‡ç« 
      icon: ğŸ“
    - name: æ‚è°ˆ
      display_name: èŠœæ¹–~æ‚è°ˆï¼
      icon: ğŸ±â€ğŸ‘“
    - name: å‰ç«¯
      display_name: å‰ç«¯çš„ä¸€äº›ä¸œè¥¿
      icon: ğŸ‘©â€ğŸ’»
  color_setting:
    text_color: black
    text_hover_color: white
    background_color: "#f2f2f2"
    background_hover_color: "#A8D6D2"
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet">${temple_html_item}</div></div>'
  plus_style: ""

# _config.yml
OhMyLive2d:
  enable: true
  CDN: https://registry.npmmirror.com/oh-my-live2d/latest/files
  # CDN: https://registry.npmmirror.com/oh-my-live2d/0.13/files/dist/index.min.js
  option:
    # importType: 'cubism2' #  å¯¼å…¥ç±»å‹, é»˜è®¤ä½¿ç”¨å…¨é‡å¯¼å…¥: complete , å¯é€‰å€¼: complete, cubism2, cubism5
    libraryUrls: # è‡ªå®šä¹‰ Cubism SDK å¤–éƒ¨èµ„æºåœ°å€
      complete: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/complete.js
      cubism2: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism2.js
      cubism5: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism5.js
    # menus:
    # items: |
    #   (defaultItems)=>{
    #    return [
    #      ...defaultItems,
    #      {
    #        id: 'github',
    #        icon: 'github-fill',
    #        title: 'æˆ‘çš„github',
    #        onClick: ()=>window.open('https://github.com/hacxy')
    #      }
    #    ]
    #   }

    # items:
    #   - id: 'github'
    #     icon: 'github-fill'
    #     title: 'æˆ‘çš„github'
    #     onClick: ()=>window.open('https://github.com/hacxy')

    mobileDisplay: false # æ˜¯å¦åœ¨ç§»åŠ¨ç«¯æ˜¾ç¤º
    models:
      - path: /live2d-model-vertin/vertin.model3.json
        mobilePosition: [-10, 23] # ç§»åŠ¨ç«¯æ—¶æ¨¡å‹åœ¨èˆå°ä¸­çš„ä½ç½®ã€‚ é»˜è®¤å€¼: [0,0] [æ¨ªåæ ‡, çºµåæ ‡]
        mobileScale: 0.5 # ç§»åŠ¨ç«¯æ—¶æ¨¡å‹çš„ç¼©æ”¾æ¯”ä¾‹ é»˜è®¤å€¼: 0.1
        mobileStageStyle: # ç§»åŠ¨ç«¯æ—¶èˆå°çš„æ ·å¼
          width: 180
          height: 166
        motionPreloadStrategy: IDLE # åŠ¨ä½œé¢„åŠ è½½ç­–ç•¥ é»˜è®¤å€¼: IDLE å¯é€‰å€¼: ALL | IDLE | NONE
        position: [-150, -30] # æ¨¡å‹åœ¨èˆå°ä¸­çš„ä½ç½®ã€‚ é»˜è®¤å€¼: [0,0] [æ¨ªåæ ‡, çºµåæ ‡]
        scale: 0.4 # æ¨¡å‹çš„ç¼©æ”¾æ¯”ä¾‹ é»˜è®¤å€¼: 0.1
        # showHitAreaFrames: false # æ˜¯å¦æ˜¾ç¤ºç‚¹å‡»åŒºåŸŸ é»˜è®¤å€¼: false
        stageStyle:
          width: 250
          height: 250
    parentElement: document.body #ä¸ºç»„ä»¶æä¾›ä¸€ä¸ªçˆ¶å…ƒç´ ï¼Œå¦‚æœæœªæŒ‡å®šåˆ™é»˜è®¤æŒ‚è½½åˆ° body ä¸­
    primaryColor: 'var(--btn-bg)' # ä¸»é¢˜è‰² æ”¯æŒå˜é‡
    sayHello: false # æ˜¯å¦åœ¨åˆå§‹åŒ–é˜¶æ®µæ‰“å°é¡¹ç›®ä¿¡æ¯
    tips:
      style:
        width: 200
        height: 60
        left: calc(50% - 20px)
        top: -100px
      mobileStyle:
        width: 180
        height: 80
        left: calc(50% - 30px)
        top: -100px
      idleTips:
        interval: 1500
        # message:
        #   - ä½ å¥½å‘€~
        #   - æ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç«™~
        # è‡ªå®šä¹‰æç¤ºè¯­ éœ€è¦ å¼•å…¥ axios åº“ ,ä¹Ÿå¯ä»¥ä½¿ç”¨å…¶ä»–æ–¹æ³•
        message: |
          function(){
            return axios.get('https://v1.hitokoto.cn?c=i')
              .then(function (response) {
                return response.data.hitokoto ;
              })
              .catch(function (error) {
                console.error(error);
              });
          }
        # wordTheDay: true
        # è‡ªå®šä¹‰  https://v1.hitokoto.cn  æ•°æ®
        # wordTheDay: |
        #   function(wordTheDayData){
        #     return `${wordTheDayData.hitokoto}    by.${wordTheDayData.from}`;
        #   }
  # then: |
  #   (oml2d)=>{
  #      setTimeout(() => {
  #     oml2d.tipsMessage('hello world', 3000, 10);
  #   }, 8000);
  #   }